import './globals.css'
import ThemeProviders from '@/provider/Theme'
import RecoilProvider from '@/provider/GlobalState'

import type { Metadata } from 'next'

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app'
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
    return (
        <html lang="en">
            <body className="dark:#202027">
                <RecoilProvider>
                    <ThemeProviders>{children}</ThemeProviders>
                </RecoilProvider>
            </body>
        </html>
    )
}
