version: "3"
services:
  nginx:
    image: nginx:latest
    container_name: nginx
    profiles: ["project_1"]
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "3000:3000"
      - "4000:4000"
      - "5432:5432"
    networks:
      - test_network

networks:
  test_network:
    external: true
